server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/oweson/leyou-config.git
  rabbitmq:
    host: 139.224.35.86
    username: leyou
    password: leyou
    virtual-host: /leyou


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
